// Generated by data-extractor on 2026-04-15T13:09:06.502Z. Do not edit manually.

// No deity 2DA found in nwsync or base game. See extraction log.
// Deity data requires manual overrides from server documentation.
export const compiledDeityCatalog = null;
