// Generated by data-extractor on 2026-04-16T21:49:39.692Z. Do not edit manually.

// No deity 2DA found in nwsync or base game. See extraction log.
// Deity data requires manual overrides from server documentation.
export const compiledDeityCatalog = null;
