// Generated by data-extractor on 2026-04-17T12:41:31.529Z. Do not edit manually.

// No deity 2DA found in nwsync or base game. See extraction log.
// Deity data requires manual overrides from server documentation.
export const compiledDeityCatalog = null;
