// Generated by data-extractor on 2026-04-17T12:41:31.803Z. Do not edit manually.

import { domainCatalogSchema } from '@data-extractor/contracts/domain-catalog';
import type { DomainCatalog } from '@data-extractor/contracts/domain-catalog';

export const compiledDomainCatalog: DomainCatalog = domainCatalogSchema.parse({
  "datasetId": "puerta-ee-2026-04-17+cf6e8aad",
  "domains": [
    {
      "description": "Dominio de Aire\nLos clérigos del dominio de Aire tienen poder sobre las criaturas de los Planos Elementales y obtienen la aptitud de lanzar conjuros de daño eléctrico.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar elementales: Puede expulsar a los elementales como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Ráfaga de viento (2), Llamar al relámpago (3), Volar (4), Relámpago zigzagueante (6), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:air-domain-power"
      ],
      "id": "domain:air",
      "label": "Aire",
      "sourceRow": 0,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [
          "spell:gust-of-wind"
        ],
        "3": [
          "spell:call-lightning"
        ],
        "4": [
          "spell:volar"
        ],
        "5": [],
        "6": [
          "spell:chain-lightning"
        ],
        "7": [],
        "8": [],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio Animal\nLos clérigos que toman el dominio Animal son capaces de convocar aliados animales más poderosos.\nAptitudes especiales y conjuros adicionales del dominio\nPermite convocar a animales más poderosos usando Convocar criatura.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Inmovilizar animal (1), Gracia felina (2), Visión verdadera (3), Dotar de consciencia (4), Polimorfarse (5), Convocar criatura IX (8), Cambiar de forma (9).",
      "grantedFeatIds": [
        "feat:animal-domain-power"
      ],
      "id": "domain:animal",
      "label": "Animal",
      "sourceRow": 1,
      "spellIds": {
        "0": [],
        "1": [
          "spell:hold-animal"
        ],
        "2": [
          "spell:cats-grace"
        ],
        "3": [
          "spell:true-seeing"
        ],
        "4": [
          "spell:awaken"
        ],
        "5": [
          "spell:polymorph-self"
        ],
        "6": [],
        "7": [],
        "8": [],
        "9": [
          "spell:shapechange"
        ]
      }
    },
    {
      "description": "Dominio de Suerte\nLos clérigos que toman el dominio de Suerte pueden convocar el poder de su deidad para escabullirse de las situaciones más peligrosas. También obtienen acceso a conjuros que mejoran sus habilidades.\nAptitudes especiales y conjuros adicionales del dominio\nBuena fortuna: El clérigo obtiene un bonificador de 1, +1 por cada 5 niveles, a la clase de armadura y tiros de salvación.. Este efecto tiene una duración de 5 asaltos + el modificador de Carisma.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Auxilio divino (1), Libertad de movimiento (3), Desplazamiento (4), De la piedra a la carne (5), Protección contra conjuros (7), Toga contra conjuros mayor (9).",
      "grantedFeatIds": [
        "feat:dominio-suerte"
      ],
      "id": "domain:pb-suerte",
      "label": "Suerte",
      "sourceRow": 2,
      "spellIds": {
        "0": [],
        "1": [
          "spell:aid"
        ],
        "2": [],
        "3": [
          "spell:freedom-of-movement"
        ],
        "4": [
          "spell:displacement"
        ],
        "5": [
          "spell:stone-to-flesh"
        ],
        "6": [],
        "7": [
          "spell:protection-from-spells"
        ],
        "8": [],
        "9": [
          "spell:greater-spell-mantle"
        ]
      }
    },
    {
      "description": "Dominio de Muerte\nLos clérigos que toman el dominio de Muerte pueden convocar una sombra mejorada y obtienen conjuros relacionados con la muerte.\nAptitudes especiales y conjuros adicionales del dominio\nAvatar del Plano Negativo: El clérigo puede convocar a una sombra que se hace más poderosa a medida que va avanzando el clérigo.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Miedo (1), Reanimar a los muertos (2), Custodia contra la muerte (3), Rematar a los vivos (4),  Asesino fantasmal (5), Enervación (6), Crear muertos vivientes mayores (7), Lamento de la banshee (9).",
      "grantedFeatIds": [
        "feat:death-domain-power"
      ],
      "id": "domain:death",
      "label": "Muerte",
      "sourceRow": 3,
      "spellIds": {
        "0": [],
        "1": [
          "spell:fear"
        ],
        "2": [
          "spell:animate-dead"
        ],
        "3": [
          "spell:death-ward"
        ],
        "4": [
          "spell:slay-living"
        ],
        "5": [
          "spell:phantasmal-killer"
        ],
        "6": [
          "spell:enervation"
        ],
        "7": [
          "spell:create-greater-undead"
        ],
        "8": [],
        "9": [
          "spell:wail-of-the-banshee"
        ]
      }
    },
    {
      "description": "Dominio de Destrucción\nLos clérigos que toman el dominio de Destrucción son capaces de dañar a constructos por medio de su fuerza de voluntad y reciben conjuros que les permiten debilitar y destruir a sus enemigos.\nAptitudes especiales y conjuros adicionales del dominio\nDebilitar constructos: Puede dañar a los constructos cuando utiliza la aptitud de expulsión.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Infligir heridas moderadas (1), Nube apestosa (3), Infligir heridas moderadas en grupo (5), Bruma ácida (6), Dedo de la muerte (7).",
      "grantedFeatIds": [
        "feat:destruction-domain-power"
      ],
      "id": "domain:destruction",
      "label": "Destrucción",
      "sourceRow": 4,
      "spellIds": {
        "0": [],
        "1": [
          "spell:inflict-moderate-wounds"
        ],
        "2": [],
        "3": [
          "spell:stinking-cloud"
        ],
        "4": [],
        "5": [
          "spell:infligirheridasmoderadasengrupo"
        ],
        "6": [
          "spell:acid-fog"
        ],
        "7": [
          "spell:finger-of-death"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Tierra\nLos clérigos del dominio de Tierra tienen poder sobre las criaturas de los Planos Elementales y obtienen conjuros que les protegen del cuerpo a cuerpo y el daño por energía.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar elementales: Puede expulsar a los elementales como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Piel pétrea (4), Barrera de energía (5), Piel pétrea mayor (6), Terremoto (7), Cuerpo férreo (8), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:earth-domain-power"
      ],
      "id": "domain:earth",
      "label": "Tierra",
      "sourceRow": 5,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [],
        "3": [],
        "4": [
          "spell:stoneskin"
        ],
        "5": [
          "spell:energy-buffer"
        ],
        "6": [
          "spell:greater-stoneskin"
        ],
        "7": [
          "spell:earthquake"
        ],
        "8": [
          "spell:cuerpoferreo"
        ],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio del Mal\nLos clérigos que toman el dominio del Mal tienen poder sobre los ajenos y obtienen conjuros que manipulan la energía negativa.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar ajenos: Puede expulsar a los ajenos como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Rayo de energía negativa (1), Explosión de energía negativa (3), Enervación (4), Crear muertos vivientes (5), Dedo de la muerte (7), Convocar criatura IX (8).",
      "grantedFeatIds": [
        "feat:evil-domain-power"
      ],
      "id": "domain:evil",
      "label": "Mal",
      "sourceRow": 6,
      "spellIds": {
        "0": [],
        "1": [
          "spell:negative-energy-ray"
        ],
        "2": [],
        "3": [
          "spell:negative-energy-burst"
        ],
        "4": [
          "spell:enervation"
        ],
        "5": [
          "spell:create-undead"
        ],
        "6": [],
        "7": [
          "spell:finger-of-death"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Fuego\nLos clérigos que toman el dominio de fuego tienen poder sobre las criaturas de los Planos Elementales y obtienen conjuros que convocan al fuego y protegen del mismo.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar elementales: Puede expulsar a los elementales como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Manos Ardientes (1), Protección contra los elementos (2), Muro de fuego (4), Barrera de energía (5), Tormenta de fuego (7), Nube incendiaria (8), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:fire-domain-power"
      ],
      "id": "domain:fire",
      "label": "Fuego",
      "sourceRow": 7,
      "spellIds": {
        "0": [],
        "1": [
          "spell:burning-hands"
        ],
        "2": [
          "spell:protection-from-elements"
        ],
        "3": [],
        "4": [
          "spell:wall-of-fire"
        ],
        "5": [
          "spell:energy-buffer"
        ],
        "6": [],
        "7": [
          "spell:fire-storm"
        ],
        "8": [
          "spell:incendiary-cloud"
        ],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio del Bien\nLos clérigos que toman el dominio del Bien tienen poder sobre los ajenos y obtienen conjuros que les protegen tanto a ellos mismos como a otros.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar ajenos: Puede expulsar a los ajenos como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Auxilio divino (1), Mente en blanco menor (3), Piel pétrea (4), Ligadura menor de los planos (5), Inmovilizar monstruo (6), Aura sagrada (7), Convocar criatura IX (8).",
      "grantedFeatIds": [
        "feat:good-domain-power"
      ],
      "id": "domain:good",
      "label": "Bien",
      "sourceRow": 8,
      "spellIds": {
        "0": [],
        "1": [
          "spell:aid"
        ],
        "2": [],
        "3": [
          "spell:lesser-mind-blank"
        ],
        "4": [
          "spell:stoneskin"
        ],
        "5": [
          "spell:lesser-planar-binding"
        ],
        "6": [
          "spell:hold-monster"
        ],
        "7": [
          "spell:aura-versus-alignment"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Curación\nLos clérigos que toman el dominio de Curación pueden curar heridas de manera más efectiva que sus hermanos y ganan acceso a conjuros de curación a una velocidad superior.\nAptitudes especiales y conjuros adicionales del dominio\nPotenciar curación: los siguientes sortilegios de curación se ejecutan como si se utilizara la dote Potenciar conjuro: Curar heridas menores, Curar heridas moderadas, Curar heridas graves y Curar heridas críticas.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Curar heridas moderadas (1), Curar heridas graves (2), Curar heridas críticas (3), Sanar (5), Restablecimiento mayor (6).",
      "grantedFeatIds": [
        "feat:healing-domain-power"
      ],
      "id": "domain:healing",
      "label": "Curación",
      "sourceRow": 9,
      "spellIds": {
        "0": [],
        "1": [
          "spell:cure-moderate-wounds"
        ],
        "2": [
          "spell:cure-serious-wounds"
        ],
        "3": [
          "spell:cure-critical-wounds"
        ],
        "4": [],
        "5": [
          "spell:heal"
        ],
        "6": [
          "spell:greater-restoration"
        ],
        "7": [],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Saber\nLos clérigos que toman el dominio de Saber ganan acceso a una lista mejorada de conjuros adicionales.\nConjuros adicionales\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Identificar (1), Apertura (2), Clariaudiencia/clarividencia (3), Visión verdadera (4), Conocimiento de leyendas (6), Premonición (8).",
      "grantedFeatIds": [
        "feat:knowledge-domain-power"
      ],
      "id": "domain:knowledge",
      "label": "Saber",
      "sourceRow": 10,
      "spellIds": {
        "0": [],
        "1": [
          "spell:identify"
        ],
        "2": [
          "spell:knock"
        ],
        "3": [
          "spell:clairaudience-and-clairvoyance"
        ],
        "4": [
          "spell:true-seeing"
        ],
        "5": [],
        "6": [
          "spell:legend-lore"
        ],
        "7": [],
        "8": [
          "spell:premonition"
        ],
        "9": []
      }
    },
    {
      "description": "Dominio de Ley\nLos clérigos que toman el dominio de Ley tienen poder sobre los ajenos y obtienen conjuros que manipulan la energía legal.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar ajenos: Puede expulsar a los ajenos como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Círculo mágico contra alineamiento (2), Martillo de los dioses (3), Inmovilizar monstruo (4), Disipación mayor (5), Aura sagrada (7), Convocar criatura IX (8).",
      "grantedFeatIds": [
        "feat:dominio-ley"
      ],
      "id": "domain:pb-ley",
      "label": "Ley",
      "sourceRow": 11,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [
          "spell:magic-circle-against-alignment"
        ],
        "3": [
          "spell:hammer-of-the-gods"
        ],
        "4": [
          "spell:hold-monster"
        ],
        "5": [
          "spell:greater-dispelling"
        ],
        "6": [],
        "7": [
          "spell:aura-versus-alignment"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Caos\nLos clérigos que toman el dominio del Caos tienen poder sobre los ajenos y obtienen conjuros que manipulan la energía caótica.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar ajenos: Puede expulsar a los ajenos como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Círculo mágico contra alineamiento (2), Martillo de los dioses (3), Inmovilizar monstruo (4), Disipación mayor (5), Aura sagrada (7), Convocar criatura IX (8).",
      "grantedFeatIds": [
        "feat:dominio-caos"
      ],
      "id": "domain:pb-caos",
      "label": "Caos",
      "sourceRow": 12,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [
          "spell:magic-circle-against-alignment"
        ],
        "3": [
          "spell:hammer-of-the-gods"
        ],
        "4": [
          "spell:hold-monster"
        ],
        "5": [
          "spell:greater-dispelling"
        ],
        "6": [],
        "7": [
          "spell:aura-versus-alignment"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio de Magia\nLos clérigos que toman el dominio de Magia ganan acceso a una lista ampliada de conjuros adicionales.\nConjuros adicionales\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Armadura de mago (1), Flecha ácida de Melf (2), Explosión de energía negativa (3), Piel pétrea (4), Tormenta de hielo (5), Protección contra conjuros (7), Disyunción de Mordenkainen (9).",
      "grantedFeatIds": [
        "feat:magic-domain-power"
      ],
      "id": "domain:magic",
      "label": "Magia",
      "sourceRow": 13,
      "spellIds": {
        "0": [],
        "1": [
          "spell:mage-armor"
        ],
        "2": [
          "spell:melfs-acid-arrow"
        ],
        "3": [
          "spell:negative-energy-burst"
        ],
        "4": [
          "spell:stoneskin"
        ],
        "5": [
          "spell:ice-storm"
        ],
        "6": [],
        "7": [
          "spell:protection-from-spells"
        ],
        "8": [],
        "9": [
          "spell:mordenkainens-disjunction"
        ]
      }
    },
    {
      "description": "Dominio Vegetal\nLos clérigos que toman el dominio Vegetal son capaces de repeler y destruir sabandijas y tienen conjuros que llaman al poder de la naturaleza para protegerse y destruir.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar sabandijas: Permite expulsar sabandijas como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Enmarañar (1), Piel robliza (2), Brotar de espinas (3), Extender enredaderas (5), Marabunta (7), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:plant-domain-power"
      ],
      "id": "domain:plant",
      "label": "Vegetal",
      "sourceRow": 14,
      "spellIds": {
        "0": [],
        "1": [
          "spell:entangle"
        ],
        "2": [
          "spell:barkskin"
        ],
        "3": [
          "spell:spike-growth"
        ],
        "4": [],
        "5": [],
        "6": [],
        "7": [
          "spell:creeping-doom"
        ],
        "8": [],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio de Protección\nLos clérigos que toman el dominio de Protección pueden protegerse del daño mediante la utilización de sus conjuros y aptitudes especiales.\nAptitudes especiales y conjuros adicionales del dominio\nProtección divina: El clérigo es capaz de lanzar una forma mejorada de Santuario que establece la CD de la salvación en 10 + modificador de Car + nivel clerical. El efecto tiene una duración de 1 asalto por nivel del lanzador + el modificador de Carisma del clérigo.\nConjuros adicionales: el clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Resistencia a los elementos (1), Protección contra los elementos (2), Globo menor de invulnerabilidad (4), Barrera de energía (5), Mente en blanco (8).",
      "grantedFeatIds": [
        "feat:protection-domain-power"
      ],
      "id": "domain:protection",
      "label": "Protección",
      "sourceRow": 15,
      "spellIds": {
        "0": [],
        "1": [
          "spell:resist-elements"
        ],
        "2": [
          "spell:protection-from-elements"
        ],
        "3": [],
        "4": [
          "spell:minor-globe-of-invulnerability"
        ],
        "5": [
          "spell:energy-buffer"
        ],
        "6": [],
        "7": [],
        "8": [
          "spell:mind-blank"
        ],
        "9": []
      }
    },
    {
      "description": "Dominio de Fuerza\nLos clérigos que toman el dominio de Fuerza son capaces de aumentar esta característica con energía divina y ganan acceso a conjuros que les hacen más fuertes y resistentes.\nAptitudes especiales y conjuros adicionales del dominio\nMaestro de la batalla: El clérigo obtiene un bonificador de +20 al ataque durante 2 asaltos.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Fuerza de toro (1), Poder divino (3), Globo de invulnerabilidad (4), Piel pétrea (5), Mano aferradora de Bigby (7), Puño cerrado de Bigby (8), Mano aplastante de Bigby (9).",
      "grantedFeatIds": [
        "feat:strength-domain-power"
      ],
      "id": "domain:strength",
      "label": "Fuerza",
      "sourceRow": 16,
      "spellIds": {
        "0": [],
        "1": [
          "spell:bulls-strength"
        ],
        "2": [],
        "3": [
          "spell:divine-power"
        ],
        "4": [
          "spell:minor-globe-of-invulnerability"
        ],
        "5": [
          "spell:stoneskin"
        ],
        "6": [],
        "7": [
          "spell:bigbys-grasping-hand"
        ],
        "8": [
          "spell:bigbys-clenched-fist"
        ],
        "9": [
          "spell:bigbys-crushing-hand"
        ]
      }
    },
    {
      "description": "Dominio de Sol\nLos clérigos que toman el dominio de Sol pueden rechazar muertos vivientes mejor que sus hermanos y obtienen conjuros que dañan a estas criaturas.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsión excepcional: Añade 1d6 a todas las pruebas de expulsión para determinar los DG máximos de muertos vivientes expulsados. Añade también 1d4 al número de muertos vivientes expulsados.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Resistencia a los elementos (1), Luz abrasadora (2), Escudo de fuego (3), Descarga flamígera (4), Rayo solar (7), Explosión solar (8).",
      "grantedFeatIds": [
        "feat:sun-domain-power"
      ],
      "id": "domain:sun",
      "label": "Sol",
      "sourceRow": 17,
      "spellIds": {
        "0": [],
        "1": [
          "spell:resist-elements"
        ],
        "2": [
          "spell:searing-light"
        ],
        "3": [
          "spell:elemental-shield"
        ],
        "4": [
          "spell:flame-strike"
        ],
        "5": [],
        "6": [],
        "7": [
          "spell:sunbeam"
        ],
        "8": [
          "spell:sunburst"
        ],
        "9": []
      }
    },
    {
      "description": "Dominio de Viaje\nLos clérigos que toman el dominio de Viaje ganan acceso a una lista ampliada de conjuros adicionales.\nConjuros adicionales\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Enmarañar (1), Telaraña (2), Volar (3), Puerta dimensional (4), Teleportar (5), Teleportar mayor (7), Magnífica mansión de Mordenkainen (9).",
      "grantedFeatIds": [
        "feat:travel-domain-power"
      ],
      "id": "domain:travel",
      "label": "Viaje",
      "sourceRow": 18,
      "spellIds": {
        "0": [],
        "1": [
          "spell:entangle"
        ],
        "2": [
          "spell:web"
        ],
        "3": [
          "spell:volar"
        ],
        "4": [
          "spell:puertadimensional"
        ],
        "5": [
          "spell:teleportar"
        ],
        "6": [],
        "7": [
          "spell:teleportarmayor"
        ],
        "8": [],
        "9": [
          "spell:magnficamansiondemordenkainen"
        ]
      }
    },
    {
      "description": "Dominio de Superchería\nLos clérigos que toman el dominio de Superchería obtienen bonificadores a las habilidades de Pícaro y ganan acceso a diversos conjuros de invisibilidad.\nAptitudes especiales y conjuros adicionales del dominio\nSuperchería divina: Bonificador igual a 1 cada 2 niveles a las pruebas de Abrir cerraduras, Buscar, Esconderse, Hurtar, Inutilizar trampa, Moverse sigilosamente y Persuasión. Este efecto dura 5 turnos + el modificador de Carisma del clérigo.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Disfrazarse (1), Invisibilidad (2), Esfera de invisibilidad (3), Confusion (4), Invisibilidad mejorada (5), Detener el tiempo (9).",
      "grantedFeatIds": [
        "feat:trickery-domain-power"
      ],
      "id": "domain:trickery",
      "label": "Superchería",
      "sourceRow": 19,
      "spellIds": {
        "0": [],
        "1": [
          "spell:disfrazarse"
        ],
        "2": [
          "spell:invisibility"
        ],
        "3": [
          "spell:invisibility-sphere"
        ],
        "4": [
          "spell:confusion"
        ],
        "5": [
          "spell:improved-invisibility"
        ],
        "6": [],
        "7": [],
        "8": [],
        "9": [
          "spell:time-stop"
        ]
      }
    },
    {
      "description": "Dominio de Guerra\nLos clérigos que toman el dominio de Guerra pueden convocar el poder de su deidad para convertirse en máquinas de destrucción. También obtienen acceso a conjuros que mejoran sus habilidades de combate.\nAptitudes especiales y conjuros adicionales del dominio\nMaestro de la batalla: Los clérigos obtienen un bonificador +1, +1 adicional cada 5 niveles, a Destreza, Constitución y las tiradas de ataque y daño. Además, este modificador se utiliza para otorgar al clérigo una reducción del daño de esa misma cantidad. El efecto durará 5 asaltos + modificador de Carisma.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Gracia felina (2), Poder divino (3), Descarga flamígera (4), Barrera de cuchillas (5), Aura de vitalidad (7), Palabra de poder aturdidor (8), Palabra de poder mortal (9).",
      "grantedFeatIds": [
        "feat:war-domain-power"
      ],
      "id": "domain:war",
      "label": "Guerra",
      "sourceRow": 20,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [
          "spell:cats-grace"
        ],
        "3": [
          "spell:divine-power"
        ],
        "4": [
          "spell:flame-strike"
        ],
        "5": [
          "spell:blade-barrier"
        ],
        "6": [],
        "7": [
          "spell:aura-of-vitality"
        ],
        "8": [
          "spell:power-word-stun"
        ],
        "9": [
          "spell:power-word-kill"
        ]
      }
    },
    {
      "description": "Dominio de Agua.\nLos clérigos que toman el dominio de Agua tienen poder sobre las criaturas de los Planos Elementales y obtienen conjuros que debilitan o matan a sus oponentes.\nAptitudes especiales y conjuros adicionales del dominio\nExpulsar elementales: Puede expulsar a los elementales como si fueran muertos vivientes.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Veneno (3), Tormenta de hielo (5), Cono de frío (6), Bruma ácida (7), Horrible marchitamiento (8), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:water-domain-power"
      ],
      "id": "domain:water",
      "label": "Agua",
      "sourceRow": 21,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [],
        "3": [
          "spell:poison"
        ],
        "4": [],
        "5": [
          "spell:ice-storm"
        ],
        "6": [
          "spell:cone-of-cold"
        ],
        "7": [
          "spell:acid-fog"
        ],
        "8": [
          "spell:horrid-wilting"
        ],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio Enano\nLos clérigos que toman el dominio Enano son más resistentes y ganan acceso a una lista ampliada de conjuros adicionales.\nAptitudes especiales y conjuros adicionales del dominio\nEl clérigo obtiene la dote 'Gran fortaleza' gratuitamente.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Resistencia de oso (1), Glifo custodio (2), Arma mágica mayor (3), Piel pétrea (5), Protección contra los conjuros (8), Enjambre elemental (9).",
      "grantedFeatIds": [
        "feat:dominio-enano"
      ],
      "id": "domain:pb-enano",
      "label": "Enano",
      "sourceRow": 22,
      "spellIds": {
        "0": [],
        "1": [
          "spell:endurance"
        ],
        "2": [
          "spell:glyph-of-warding"
        ],
        "3": [
          "spell:greater-magic-weapon"
        ],
        "4": [],
        "5": [
          "spell:stoneskin"
        ],
        "6": [],
        "7": [],
        "8": [
          "spell:protection-from-spells"
        ],
        "9": [
          "spell:elemental-swarm"
        ]
      }
    },
    {
      "description": "Dominio Élfico\nLos clérigos que toman el dominio Élfico son más competentes con el arco y ganan acceso a una lista ampliada de conjuros adicionales.\nAptitudes especiales y conjuros adicionales del dominio\nEl clérigo obtiene la dote 'Disparo a bocajarro' gratuitamente.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Impacto verdadero (1), Gracia felina (2), Pasar sin dejar rastro (3), Zancada arbórea (4), Equilibrio de la naturaleza (8), Explosión solar (9).",
      "grantedFeatIds": [
        "feat:dominio-elfico"
      ],
      "id": "domain:pb-elfico",
      "label": "Élfico",
      "sourceRow": 23,
      "spellIds": {
        "0": [],
        "1": [
          "spell:true-strike"
        ],
        "2": [
          "spell:cats-grace"
        ],
        "3": [
          "spell:pasarsindejarrastro"
        ],
        "4": [
          "spell:zancadaarborea"
        ],
        "5": [],
        "6": [],
        "7": [],
        "8": [
          "spell:natures-balance"
        ],
        "9": [
          "spell:sunburst"
        ]
      }
    },
    {
      "description": "Dominio Gnomo\nLos clérigos que toman el dominio Gnomo son capaces de desaparecer a voluntad y ganan acceso a una lista ampliada de conjuros adicionales.\nAptitudes especiales y conjuros adicionales del dominio\nImágen ilusoria: El clérigo es capaz de lanzar una forma mejorada de Invisivilidad. El efecto tiene una duración de 1 asalto por nivel de lanzador + el modificador de Carisma del clérigo.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Rociada de color (1), Invisibilidad (2), Esfera de invisibilidad (3), Invisivilidad mejorada (4), Ceguera/sordera de masas (7), Convocar criatura IX (8).",
      "grantedFeatIds": [
        "feat:dominio-gnomo"
      ],
      "id": "domain:pb-gnomo",
      "label": "Gnomo",
      "sourceRow": 24,
      "spellIds": {
        "0": [],
        "1": [
          "spell:color-spray"
        ],
        "2": [
          "spell:invisibility"
        ],
        "3": [
          "spell:invisibility-sphere"
        ],
        "4": [
          "spell:improved-invisibility"
        ],
        "5": [],
        "6": [],
        "7": [
          "spell:mass-blindness-and-deafness"
        ],
        "8": [],
        "9": []
      }
    },
    {
      "description": "Dominio Mediano\nLos clérigos que toman el dominio Mediano son más sigilosos y ágiles, y ganan acceso a una lista ampliada de conjuros adicionales.\nAptitudes especiales y conjuros adicionales del dominio\nMaestría mediana: El clérigo una vez al día puede sumar su modificador de Carisma a sus pruebas de Esconderse, Moverse sigilosamente, Saltar y Trepar. El efecto dura 5 minutos.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Gracia felina (2), Libertad de movimiento (3), Puerta dimensional (4), Palabra de regreso (5), Terremoto (7), Premonición (8).",
      "grantedFeatIds": [
        "feat:dominio-mediano"
      ],
      "id": "domain:pb-mediano",
      "label": "Mediano",
      "sourceRow": 25,
      "spellIds": {
        "0": [],
        "1": [],
        "2": [
          "spell:cats-grace"
        ],
        "3": [
          "spell:freedom-of-movement"
        ],
        "4": [
          "spell:puertadimensional"
        ],
        "5": [
          "spell:palabraderegreso"
        ],
        "6": [],
        "7": [
          "spell:earthquake"
        ],
        "8": [
          "spell:premonition"
        ],
        "9": []
      }
    },
    {
      "description": "Dominio Orco\nLos clérigos que toman el dominio Orco ganan acceso a una lista ampliada de conjuros adicionales.\nAptitudes especiales y conjuros adicionales del dominio\nCastigo orco: El clérigo una vez al día puede obtiener un bonificador a la tirada de daño igual a su nivel de clérigo. Recibe también un bonificador +4 a la tirada de ataque contra elfos y enanos. El efecto tiene una duración de 2 asaltos.\nEl clérigo obtiene acceso a los siguientes sortilegios en el nivel de conjuro especificado: Miedo (1), Plegaria (2), Poder divino (3), Nube aniquiladora (5), Palabra de poder aturdidor (7), Palabra de poder mortal (9).",
      "grantedFeatIds": [
        "feat:dominio-orco"
      ],
      "id": "domain:pb-orco",
      "label": "Orco",
      "sourceRow": 26,
      "spellIds": {
        "0": [],
        "1": [
          "spell:fear"
        ],
        "2": [
          "spell:prayer"
        ],
        "3": [
          "spell:divine-power"
        ],
        "4": [],
        "5": [
          "spell:cloudkill"
        ],
        "6": [],
        "7": [
          "spell:power-word-stun"
        ],
        "8": [],
        "9": [
          "spell:power-word-kill"
        ]
      }
    }
  ],
  "schemaVersion": "1"
});
