/**
 * TypeScript catalog emitter.
 *
 * Generates TypeScript source files from assembled catalog data. Each output
 * file contains a typed export const declaration that is validated through its
 * Zod schema at parse time (T-05.1-19 mitigation).
 *
 * T-05.1-17 mitigation: Generated files contain only the datasetId (manifest
 * hash based), never machine-local filesystem paths.
 *
 * @module
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EmitOptions {
  /** Export variable name, e.g. "compiledClassCatalog". */
  catalogName: string;
  /** Contract module path, e.g. "@data-extractor/contracts/class-catalog". */
  schemaImport: string;
  /** Zod schema export name, e.g. "classCatalogSchema". */
  schemaName: string;
  /** TypeScript type name, e.g. "ClassCatalog". */
  typeName: string;
  /** The assembled catalog data object. */
  data: unknown;
}

// ---------------------------------------------------------------------------
// Emitter
// ---------------------------------------------------------------------------

/**
 * Generate a TypeScript source string for a compiled catalog file.
 *
 * The output file validates the data through its Zod schema at import time,
 * ensuring invalid data fails the import (T-05.1-19).
 */
export function emitTypescriptCatalog(options: EmitOptions): string {
  const { catalogName, schemaImport, schemaName, typeName, data } = options;

  const timestamp = new Date().toISOString();
  const payload = JSON.stringify(data, null, 2);

  return [
    `// Generated by data-extractor on ${timestamp}. Do not edit manually.`,
    '',
    `import { ${schemaName} } from '${schemaImport}';`,
    `import type { ${typeName} } from '${schemaImport}';`,
    '',
    `export const ${catalogName}: ${typeName} = ${schemaName}.parse(${payload});`,
    '',
  ].join('\n');
}

/**
 * Write a TypeScript catalog file to disk. Creates the output directory if
 * it does not exist.
 */
export function writeTypescriptCatalog(outputPath: string, content: string): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, 'utf-8');
}
