export const shellCopyEs = {
  footer: {
    datasetAria: 'Versión del ruleset y del dataset en uso',
  },
  resumen: {
    heading: 'Resumen del personaje',
    datasetHeadingAria: 'Versión del ruleset y del dataset de esta build',
    identityBlockHeading: 'Identidad y atributos',
    progressionBlockHeading: 'Progresión',
    skillsBlockHeading: 'Habilidades',
    columnLabels: {
      attribute: 'Atributo',
      total: 'Total',
      modifier: 'Mod.',
      level: 'Nivel',
      className: 'Clase',
      bab: 'BAB',
      fortitude: 'Fort.',
      reflex: 'Ref.',
      will: 'Vol.',
      generalFeat: 'Dote general',
      classFeat: 'Dote de clase',
      skill: 'Habilidad',
      ranks: 'Rangos',
      abilityMod: 'Mod. atr.',
      skillTotal: 'Total',
    },
    attributeLabels: {
      str: 'Fuerza',
      dex: 'Destreza',
      con: 'Constitución',
      int: 'Inteligencia',
      wis: 'Sabiduría',
      cha: 'Carisma',
    },
    emptyNamePlaceholder: 'Sin nombre',
    notAvailable: '—',
    actions: {
      save: 'Guardar',
      load: 'Cargar',
      export: 'Exportar JSON',
      import: 'Importar JSON',
      share: 'Compartir',
    },
    loadingState: 'Cargando slots…',
    noSlotsMessage: 'No hay builds guardadas todavía.',
  },
  persistence: {
    saveDialog: {
      title: 'Guardar build',
      body: 'Escribe un nombre para esta build. Usaremos ese nombre como identificador del slot.',
      nameLabel: 'Nombre',
      namePlaceholder: 'mi paladín tier-1',
      confirm: 'Guardar',
      cancel: 'Cancelar',
    },
    overwriteDialog: {
      title: 'El nombre ya existe',
      body: 'Ya hay una build guardada con ese nombre. ¿Quieres sobrescribirla?',
    },
    loadDialog: {
      title: 'Cargar build',
      body: 'Selecciona una build guardada. Reemplazará el estado actual.',
      cancel: 'Cancelar',
    },
    importError: 'El archivo no se pudo importar: {reason}',
    importSuccess: 'Build importada correctamente.',
    saveSuccess: 'Build "{name}" guardada.',
    loadSuccess: 'Build "{name}" cargada.',
    privateModeUnavailable: 'Guardado local no disponible en este modo del navegador.',
    incompleteBuild:
      'Completa raza y alineamiento antes de guardar, exportar o compartir la build.',
    versionMismatch: {
      title: 'Versión incompatible',
      body: 'Esta build usa una versión de reglas o dataset distinta a la que usa este planner. No se puede cargar con exactitud — las reglas pueden haber cambiado y la build dejaría de ser legal.',
      rulesetLabel: 'Ruleset',
      datasetLabel: 'Dataset',
      note: 'Descarga el JSON para conservar la build tal cual, o cancela para mantener tu construcción actual.',
      downloadJson: 'Descargar JSON',
      cancel: 'Cancelar',
    },
    shareError: {
      title: 'URL no válida',
      emptyPayload: 'La URL de compartir no contiene una build.',
      invalidPayload: 'La URL de compartir no se pudo leer. Pide al remitente una versión nueva.',
      returnHome: 'Volver',
    },
    shareLoading: 'Cargando build compartida…',
    shareSuccess: 'Build compartida cargada.',
    shareFallback: 'Build demasiado grande para URL. Descarga el JSON para compartirla.',
  },
  appTitle: 'Planificador de personaje',
  subtitle: 'Puerta de Baldur · Neverwinter Nights EE',
  primaryAction: 'Continuar construcción',
  menuLabel: 'Abrir navegación',
  closeMenuLabel: 'Cerrar navegación',
  summaryToggleLabel: 'Mostrar u ocultar resumen',
  summaryHeading: 'Resumen del personaje',
  summaryFields: {
    character: 'Personaje',
    targetLevel: 'Nivel objetivo',
    dataset: 'Conjunto de datos',
    skillBlockedLevels: 'Niveles bloqueados',
    skillConfiguredLevel: 'Habilidades hasta',
    skillRemainingPoints: 'Restantes en habilidades',
    skillSpentPoints: 'Gastados en habilidades',
    validation: 'Validación',
    planState: 'Estado del plan',
  },
  summaryValues: {
    character: 'Sin configuración',
    targetLevel: '1-16',
    dataset: 'pendiente',
    validation: 'No evaluada',
    planState: 'Base de interfaz',
  },
  foundation: {
    blockedChoice:
      'Elección bloqueada: completa el paso anterior o cambia la opción marcada para continuar.',
    confirmOrigin: 'Confirmar origen',
    currentStateBody:
      'Define el origen para desbloquear la base del personaje.',
    currentStateHeading: 'Estado actual',
    lockedAbilitiesBody:
      'Selecciona raza, subraza y alineamiento en Construcción para desbloquear Atributos.',
    lockedAbilitiesHeading: 'El origen del personaje sigue incompleto',
    planStates: {
      blocked: 'Origen incompleto',
      invalid: 'Base en conflicto',
      ready: 'Origen definido',
    },
    remainingPoints: 'Puntos restantes',
    resetBase:
      'Reiniciar base: se perderán el origen y las características iniciales.',
    spentPoints: 'Puntos gastados',
    stepHints: {
      alignmentLocked: 'La alineación se activa después de elegir la raza.',
      subraceLocked: 'La subraza se activa después de elegir la raza.',
    },
    steps: {
      alignment: 'Alineamiento',
      race: 'Raza',
      subrace: 'Subraza',
    },
  },
  progression: {
    abilityHeading: 'Aumento de característica',
    abilityHelper:
      'Este nivel concede un aumento de característica que se reflejará en Atributos.',
    classSectionHeading: 'Clase del nivel',
    editOrigin: 'Editar origen',
    foundationStripHeading: 'Base del personaje',
    gainsHeading: 'Ganancias del nivel',
    levelLabel: 'Nivel',
    levelSheetHeading: 'Hoja del nivel',
    planStates: {
      empty: 'Sin progresión',
      inProgress: 'Progresión en curso',
      invalid: 'Ruta inválida',
      ready: 'Lista para habilidades',
      repair: 'Progresión en reparación',
    },
    placeholderBody: 'Selecciona una clase para empezar la progresión.',
    railHeading: 'Progresión 1-16',
    repairCallout:
      'Este nivel se conserva, pero depende de corregir decisiones anteriores.',
    requirementsHeading: 'Requisitos de entrada',
    statuses: {
      blocked: 'Bloqueada',
      illegal: 'Inválida',
      legal: 'Legal',
      pending: 'Pendiente',
    },
  },
  skills: {
    availablePointsLabel: 'Puntos disponibles',
    capLabel: 'Tope',
    classLabel: 'Clase',
    classSkillLabel: 'Clase',
    crossClassSkillLabel: 'Transclase',
    decreaseRankLabel: 'Reducir rango',
    emptyStateBody:
      'Completa una progresión válida en Construcción para repartir rangos por nivel.',
    emptyStateHeading: 'Las habilidades siguen bloqueadas',
    errorState:
      'Reparto bloqueado: revisa la clase, la Inteligencia o la restricción marcada y corrige el nivel anterior para continuar.',
    increaseRankLabel: 'Aumentar rango',
    invalidLevelHint: 'El reparto de este nivel supera los límites permitidos.',
    invalidRankHint: 'Ajusta el rango para mantener el reparto dentro del límite legal.',
    lockedBody:
      'Completa una progresión válida en Construcción para repartir rangos por nivel.',
    nextCostLabel: 'Siguiente coste',
    railHeading: 'Habilidades 1-16',
    rankLabel: 'Rango',
    remainingPointsLabel: 'Puntos restantes',
    repairCallout:
      'Este nivel conserva sus rangos, pero depende de corregir decisiones anteriores.',
    repairRailLabel: 'Depende del nivel',
    sheetHeading: 'Hoja de habilidades',
    spentPointsLabel: 'Puntos gastados',
    statsAllocatedSkillsLabel: 'Habilidades con rangos',
    statsCapsCostsHeading: 'Topes y costes',
    statsDescription:
      'Lectura técnica del snapshot activo de habilidades: totales, topes, costes y bloqueos sin edición.',
    statsPenaltiesHeading: 'Penalizaciones y bloqueos',
    statsTotalsHeading: 'Totales',
    trainedOnlyLabel: 'Solo entrenada',
    planStates: {
      empty: 'Sin reparto de habilidades',
      inProgress: 'Habilidades en curso',
      ready: 'Habilidades listas',
      repair: 'Habilidades en reparacion',
    },
  },
  feats: {
    classFeatStepTitle: 'Dote de clase',
    classFeatConfirm: 'Confirmar dote de clase',
    emptyStateBody: 'Completa una progresion valida en Construccion para seleccionar dotes por nivel.',
    emptyStateBodyPerLevel: 'Selecciona una clase para este nivel antes de asignar dotes.',
    emptyStateHeading: 'Las dotes siguen bloqueadas',
    errorState: 'Seleccion no permitida: revisa los requisitos marcados y corrige el paso anterior.',
    generalFeatStepTitle: 'Dote general',
    generalFeatConfirm: 'Confirmar dote general',
    noSearchResults: 'Ninguna dote coincide con la busqueda.',
    planStates: {
      empty: 'Sin dotes seleccionadas',
      inProgress: 'Dotes en curso',
      ready: 'Dotes listas',
      repair: 'Dotes en reparacion',
    },
    prereqPrefix: 'Requiere:',
    prereqFulfilled: '(cumplido)',
    prereqFeatNotTaken: '(no tomada)',
    prereqFeatTaken: '(tomada)',
    prereqNoneMet: '(ninguna tomada)',
    removeFeatTitle: 'Quitar dote',
    removeFeatBody: 'Quitar {featName} invalidara {dependentFeatName} en el nivel {level}. Continuar?',
    removeFeatConfirm: 'Quitar dote',
    removeFeatCancel: 'Cancelar',
    searchPlaceholder: 'Buscar dotes...',
    sectionClassFeats: 'Dotes de clase',
    sectionGeneralFeats: 'Dotes generales',
    sheetTabTotal: '{count} dotes',
    sheetTabInvalid: '{count} invalidas',
    autoGrantedLabel: 'Automatica',
    slotPromptClassAvailable: 'Dote de clase disponible.',
    slotPromptGeneralAvailable: 'Dote general disponible.',
  },
  stepper: {
    heading: 'Creacion de personajes',
    originHeading: 'Origen',
    progressionHeading: 'Progresion',
    originSteps: {
      race: 'Raza',
      alignment: 'Alineamiento',
      attributes: 'Atributos',
    },
    levelSubSteps: {
      class: 'Clase',
      skills: 'Habilidades',
      feats: 'Dotes',
    },
    sheetTabs: {
      stats: 'Estadisticas',
      skills: 'Habilidades',
      feats: 'Dotes',
    },
    characterSheetHeading: 'Hoja de personaje',
    emptySheetHeading: 'La hoja aun esta vacia',
    emptySheetBody: 'Empieza seleccionando una raza para definir la base de tu personaje.',
    blockedStepHint: 'Completa el paso anterior para desbloquear esta opcion.',
    levelEmptyHint: 'Selecciona una clase para empezar este nivel.',
    errorState: 'Seleccion no permitida: revisa los requisitos marcados y corrige el paso anterior.',
    resetOriginLabel: 'Reiniciar origen',
    resetOriginConfirm: 'Se perderan el origen y los atributos iniciales. Continuar?',
    resetLevelLabel: 'Reiniciar nivel',
    resetLevelConfirm: 'Se perderan las decisiones de este nivel. Continuar?',
    resetAllLabel: 'Reiniciar todo',
    resetAllConfirm: 'Se perdera toda la construccion del personaje. Continuar?',
    resumenLabel: 'Resumen',
    utilidadesLabel: 'Utilidades',
    openNav: 'Menú',
    closeNav: 'Cerrar menú',
    jugarLabel: 'Jugar',
    reiniciarLabel: 'Reiniciar',
    cancelarLabel: 'Cancelar',
    stepTitles: {
      race: 'Selecciona la raza de tu personaje',
      alignment: 'Selecciona el alineamiento del personaje',
      attributes: 'Ajusta las caracteristicas iniciales',
      class: 'Selecciona la clase del nivel',
      skills: 'Distribuir puntos de habilidad',
      feats: 'Selecciona las dotes del nivel',
    },
  },
  emptyStateHeading: 'La hoja aún está vacía',
  emptyStateBody:
    'Empieza en Construcción para fijar la base del personaje y desbloquear el resto del planificador.',
  sections: {
    build: {
      description:
        'Base del personaje, identidad y hitos principales de la construcción.',
      heading: 'Construcción',
      highlights: ['Base del personaje', 'Ruta principal', 'Marcadores iniciales'],
      label: 'Construcción',
    },
    skills: {
      description:
        'Editor por nivel para repartir rangos, revisar topes y reparar bloqueos sin salir de la hoja activa.',
      heading: 'Habilidades',
      highlights: ['Habilidades 1-16', 'Hoja de habilidades', 'Reparación preservada'],
      label: 'Habilidades',
    },
    abilities: {
      description:
        'Panel base para atributos, aumentos y prerequisitos derivados.',
      heading: 'Atributos',
      highlights: ['Valores base', 'Aumentos', 'Dependencias futuras'],
      label: 'Atributos',
    },
    stats: {
      description:
        'Vista técnica de solo lectura para seguir topes, costes y bloqueos del snapshot de habilidades.',
      heading: 'Estadísticas técnicas',
      highlights: ['Totales', 'Topes y costes', 'Penalizaciones activas'],
      label: 'Estadísticas',
    },
    summary: {
      description:
        'Espacio final para revisar la construcción completa antes de compartirla.',
      heading: 'Resumen',
      highlights: ['Vista global', 'Checklist final', 'Preparado para compartir'],
      label: 'Resumen',
    },
    utilities: {
      description:
        'Caja de utilidades futura para importación, exportación y soporte de datos.',
      heading: 'Utilidades',
      highlights: ['Importar', 'Exportar', 'Herramientas futuras'],
      label: 'Utilidades',
    },
  },
} as const;

export type PlannerSectionCopy =
  (typeof shellCopyEs.sections)[keyof typeof shellCopyEs.sections];

export type PlannerStepperCopy = typeof shellCopyEs.stepper;
